# Generated by Django 4.2 on 2026-01-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='katha_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='payment_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=50)),
                ('address', models.CharField(default='manchiryal', max_length=100)),
                ('type', models.CharField(default='normal', max_length=100)),
                ('mode', models.CharField(default='cash', max_length=100)),
                ('amount', models.CharField(max_length=20)),
            ],
        ),
    ]
