# Generated by Django 4.2 on 2026-01-03 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_katha_table_payment_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment_table',
            name='password',
        ),
    ]
