# Generated by Django 4.2 on 2026-01-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_payment_table_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_table',
            name='total',
            field=models.IntegerField(default=1, max_length=20),
        ),
    ]
