# Generated by Django 4.2 on 2026-01-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_payment_table_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_table',
            name='total',
            field=models.IntegerField(default=1),
        ),
    ]
