# Generated by Django 4.2 on 2026-01-06 11:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_payment_table_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_table',
            name='purchase_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
